Implement multi-block uncover-live
mfekadu/rc pull request #38
Opened 2019-09-09 20:54 UTC by mfekadu

resolves #28

2019-09-10 20:50 UTC, johnvtan requested changes
I think the test cases might be wrong - maybe I'm misunderstanding something though

2019-09-10 20:50 UTC, johnvtan commented on testing/uncover-live-tests.rkt
> +     (,(set),(set)    ,(set)                 ,(set))
Shouldn't `x` be alive on the `jmp block176` instruction?

2019-09-10 20:50 UTC, johnvtan commented on testing/uncover-live-tests.rkt
> +     (,(set),(set)    ,(set)                 ,(set))
Same as other comment

2019-09-10 20:50 UTC, johnvtan commented on testing/uncover-live-tests.rkt
> +; NOTE: the ,@ syntax will splice the elements of list into a "quasiquoted list"
cool!

2019-09-10 20:51 UTC, johnvtan commented on testing/uncover-live-tests.rkt
> +     (,(set),(set)    ,(set)                 ,(set))
I realize now that this wasn't the best line to make a reference to

2019-09-10 21:42 UTC, mfekadu commented
## Setup Before Iterating Over Blocks
**Consider the following:**
* `given-blocks` 
* the mutable `given-hash` 
* and `given-g`
```racket
(define given-blocks
  '((block () (label block177) (movq (int 2) (var x)) (jmp block176))
    (block () (label block178) (movq (int 3) (var x)) (jmp block176))
    (block () (label start) (cmpq (int 1) (int 1)) (jmp-if e block177) (jmp block178))
    (block () (label block176) (movq (var x) (reg rax)) (jmp conclusion))))

; NOTE: this hashtable is mutable
(define given-hash (make-hash
                    `((block177 ,@(first given-blocks))
                      (block178 ,@(second given-blocks))
                      (start ,@(third given-blocks))
                      (block176 ,@(fourth given-blocks)))))

(define dag_adj_matrix_of_given_blocks
  '((block177 block176)
    (block178 block176)
    (start block177 block178)
    (block176 conclusion)))
(define given-g (unweighted-graph/adj dag_adj_matrix_of_given_blocks))
```

**The `get-LAS-from-blocks` function will iterate over the vertices `vs`**
```racket
> (define vs (remove 'conclusion (reverse (tsort given-g))))
> vs
'(block176 block178 block177 start)
```

## First Iteration
**On the _first_ iteration consider the block `b`**
```racket
> (define b (hash-ref given-hash (first vs)))
> b
'(block () (label block176) (movq (var x) (reg rax)) (jmp conclusion))
```

**The _initial set_ for calculating the LAS here is the _empty set_**
```racket
> (define init_set (set))
> (define instrs (drop b 2))
> instrs
'((label block176) (movq (var x) (reg rax)) (jmp conclusion))
> (get-live-after-sets instrs init_set)
(list (set 'x) (set 'x) (set) (set))
```

## Second Iteration
**On the _second_ iteration consider the block `b`**
```racket
> (define b (hash-ref given-hash (second vs)))
> b
'(block () (label block178) (movq (int 3) (var x)) (jmp block176))
```

**The _initial set_ for calculating the LAS here is the _previously calculated set_**
```racket
> (define prev-LAS-list (list (set 'x) (set 'x) (set) (set)))
> (define init_set  (first prev-LAS-list) )
> init_set
(set 'x)
> (define instrs (drop b 2))
> instrs
'((label block178) (movq (int 3) (var x)) (jmp block176))
```

**Recall that the calculation of the LAS is:**
* `{ L_after - Write_vars } U { Read_vars }`
```racket
> (get-live-after-sets instrs init_set)
(list (set) (set) (set) (set))
```

## Third Iteration
**On the _third_ iteration consider the block `b`**
```racket
> (define b (hash-ref given-hash (third vs)))
> b
'(block () (label block177) (movq (int 2) (var x)) (jmp block176))
```

**The _initial set_ for calculating the LAS here is the _previously calculated set_**
```racket
> (define prev-LAS-list (list (set) (set) (set) (set)) )
> (define init_set  (first prev-LAS-list) )
> init_set
(set)
> (define instrs (drop b 2))
> instrs
'((label block177) (movq (int 2) (var x)) (jmp block176))
> (get-live-after-sets instrs init_set)
(list (set) (set) (set) (set))
```

## Fourth Iteration (last)
**On the _fourth_ iteration consider the block `b`**
```racket
> (define b (hash-ref given-hash (fourth vs)))
> b
'(block
  ()
  (label start)
  (cmpq (int 1) (int 1))
  (jmp-if e block177)
  (jmp block178))
```

**The _initial set_ for calculating the LAS here is the _previously calculated set_**
```racket
> (define prev-LAS-list (list (set) (set) (set) (set)) )
> (define init_set  (first prev-LAS-list) )
> init_set
(set)
> (define instrs (drop b 2))
> instrs
'((label start) (cmpq (int 1) (int 1)) (jmp-if e block177) (jmp block178))
> (get-live-after-sets instrs init_set)
(list (set) (set) (set) (set) (set))
```

## A list of each LAS from the above iterations
```
(list 
    (list (set 'x) (set 'x) (set) (set))
    (list (set) (set) (set) (set))
    (list (set) (set) (set) (set))
    (list (set) (set) (set) (set) (set)))
```


## The list of live-after sets above matches the expectation from the test cases copied below:
```racket
(define expect-blocks
  `((block
     ; init set of block176 is (set 'x)
     ; Live-After-Set of the "label" instruction is (set 'x)
     ; after that nothing is alive because it will retq
     (,(set 'x),(set 'x) ,(set)                   ,(set))
     (label block176)     (movq (var x) (reg rax)) (jmp conclusion))
    (block
     (,(set),(set)    ,(set)                 ,(set))
     (label block178)  (movq (int 3) (var x)) (jmp block176))
    (block
     (,(set),(set)    ,(set)                 ,(set))
     (label block177)  (movq (int 2) (var x)) (jmp block176))
    (block
     (,(set),(set) ,(set)                  ,(set)               ,(set))
     (label start)  (cmpq (int 1) (int 1))  (jmp-if e block177)  (jmp block178))))

(check-equal? expect-blocks (get-LAS-from-blocks given-hash given-g))
```

2019-09-10 22:04 UTC, mfekadu commented
@johnvtan, sorry for the giant comment, but does the last section titled "But wait" show the issue you mentioned in your comment?

2019-09-11 00:56 UTC, mfekadu reviewed
fixed issues with tests in uncover-live and new tests are now passing

2019-09-11 01:06 UTC, mfekadu commented
```
> ./run_tests.sh

Running assign-homes tests...
assign homes tests finished

Running ec-tests...
ec tests finished

Running patch instructions tests...
patch instructions tests pass

Running print-x86 tests...
print-x86 tests finished

Running rco tests...
rco tests finished

Running select instructions tests...
select instructions tests finished

Running uncover locals tests...
uncover locals tests finished

Running uncover-live tests...
uncover-live tests finished

Running uniquify tests...
uniquify tests finished

Running graph tests...
Graph tests finished running

Running make-interference tests
make interference tests done

Running allocate-registers tests
allocate registers test done

Running typecheck tests
Typecheck tests finished

Running shrink tests
shrink tests finished
>
```

2019-09-11 15:59 UTC, johnvtan approved these changes
Looks good!

2019-09-11 18:20 UTC, merged